apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: garage
data:
  DB_USER: dev_user
  DB_PASSWORD: dev1234567890
  DB_NAME: dev_db
  CI_DB_USERNAME: test_user
  CI_DB_PASSWORD: test1234567890
  CI_DB_NAME: test_db
  PROD_DB_USERNAME: prod_user
  PROD_DB_PASSWORD: prod1234567890
  PROD_DB_NAME: prod_db
  PROD_DB_PORT: "3306"
  MESSAGE_BUS_USERNAME: guest
  MESSAGE_BUS_PASSWORD: guest
  MESSAGE_BUS: rabbitmq-service
  MESSAGE_BUS_TIMEOUT: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: garage
  labels:
    app: customer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: pitstop-customer-service
        image: ziyadmabrouk/pitstop-customer:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: service-config
        env:
        - name: DB_HOST
          value: customer-database-service
        - name: PROD_DB_HOSTNAME
          value: customer-database-service
        - name: PORT
          value: "3001"
        - name: SERVICE_NAME
          value: PitstopCustomerService
---
apiVersion: v1
kind: Service
metadata:
  name: pitstop-customer-service
  namespace: garage
spec:
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-deployment
  namespace: garage
  labels:
    app: vehicle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle
  template:
    metadata:
      labels:
        app: vehicle
    spec:
      containers:
      - name: pitstop-vehicle-service
        image: ziyadmabrouk/pitstop-vehicle:latest
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: service-config
        env:
        - name: DB_HOST
          value: vehicle-database-service
        - name: PROD_DB_HOSTNAME
          value: vehicle-database-service
        - name: PORT
          value: "3002"
        - name: SERVICE_NAME
          value: PitstopVehicleService
---
apiVersion: v1
kind: Service
metadata:
  name: pitstop-vehicle-service
  namespace: garage
spec:
  selector:
    app: vehicle
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-deployment
  namespace: garage
  labels:
    app: workshop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop
  template:
    metadata:
      labels:
        app: workshop
    spec:
      containers:
      - name: pitstop-workshop-service
        image: ziyadmabrouk/pitstop-workshop-planning:latest
        ports:
        - containerPort: 3003
        envFrom:
        - configMapRef:
            name: service-config
        env:
        - name: DB_HOST
          value: workshop-database-service
        - name: PROD_DB_HOSTNAME
          value: workshop-database-service
        - name: PORT
          value: "3003"
        - name: SERVICE_NAME
          value: PitstopWorkshopService
---
apiVersion: v1
kind: Service
metadata:
  name: pitstop-workshop-service
  namespace: garage
spec:
  selector:
    app: workshop
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003