apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: garage
  labels:
    app: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: pitstop-webapp
        image: ziyadmabrouk/pitstop-webapp:1.0.0
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: garage
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081